* [Vectorization](#vect)
* [Vectorizing Logistic Regression](#vectlogreg)
* [Broadcasting](#broadcasting)
* [Python Numpy](#numpy)
* [Explanation of Logistic Regression Cost function](#explanation-of-logistic-regression-cost-function)

<img id="vect" src="https://i.imgur.com/TxXjiYe.png" style="width:650px;height:370px; float: left;"></a>

In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)
a = a.reshape(4,1)
print(a)

[1 2 3 4]
[[1]
 [2]
 [3]
 [4]]


In [2]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop version:" + str(1000*(toc-tic)) + "ms")

250031.80539316736
Vectorized version:16.18051528930664ms
250031.80539316876
For loop version:364.551305770874ms


<img src="https://i.imgur.com/dazXdzS.png" style="width:650px;height:380px; float: left;"></a>

<img src="https://i.imgur.com/TAYpdTB.png" style="width:650px;height:380px; float: left;"></a>

<img src="https://i.imgur.com/kWcoJQh.png" style="width:650px;height:380px; float: left;"></a>
getting rid of one for-loop

<img id="vectlogreg" src="https://i.imgur.com/H42svVk.png" style="width:650px;height:380px; float: left;"></a>
$$z = [z^{(1)}, ..., z^{(m)}] $$
$$= [w^{T}x^{(1)}+b, ..., w^{T}x^{(m)}+b] $$
$$= np.dot(w\cdot T, x) + b$$

$$A = \sigma(z) $$
$$= [\sigma(w^{T}x^{(1)}+b), ..., \sigma(w^{T}x^{(m)}+b)] $$
$$= [a^{(1)}, ... , a^{(m)}]$$

<img src="https://i.imgur.com/Xng06L5.png" style="width:650px;height:380px; float: left;"></a>
getting rid of all for-loops

<img src="https://i.imgur.com/SAyvy3n.png" style="width:650px;height:380px; float: left;"></a>
remove all for-loops

<img id="broadcasting" src="https://i.imgur.com/yKUl3eP.png" style="width:650px;height:400px; float: left;"></a>

In [3]:
import numpy as np

A = np.array([[56.0, 0.42, 1.0, 68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])

print(A.sum(axis=0))
print(A.sum(axis=1))

[ 59.   239.42 152.    76.9 ]
[125.42 165.2  236.7 ]


In [4]:
cal = A.sum(axis=0)
print(cal)

percentage = A/cal.reshape(1,4)
print(percentage)

[ 59.   239.42 152.    76.9 ]
[[0.94915254 0.00175424 0.00657895 0.88426528]
 [0.02033898 0.43438309 0.34210526 0.10403121]
 [0.03050847 0.56386267 0.65131579 0.01170351]]


<img src="https://i.imgur.com/W3neiIl.png" style="width:650px;height:400px; float: left;"></a>

<img src="https://i.imgur.com/6TyoPUd.png" style="width:650px;height:400px; float: left;"></a>

<img id="numpy" src="https://i.imgur.com/ydP5Lq3.png" style="width:620px;height:340px; float: left;"></a>
DO NOT USE $$a=np.random.randn(5)$$

USE $$a=np.random.randn(5,1)$$

In [5]:
import numpy as np

a = np.random.randn(5)
print(a)

[ 1.12708572  0.35537609  0.56676435 -1.30830495  0.22231351]


In [6]:
#DO NOT USE rank 1 array(neither row/column vector)
print(a.shape)

(5,)


In [7]:
print(a.T)

[ 1.12708572  0.35537609  0.56676435 -1.30830495  0.22231351]


In [8]:
print(np.dot(a,a.T))

3.4789213422102963


In [9]:
# column vector
a = np.random.randn(5,1)
print(a)

[[ 1.90098874]
 [-0.61562185]
 [-1.69328732]
 [-0.96192453]
 [ 1.01334347]]


In [10]:
print(a.T)

[[ 1.90098874 -0.61562185 -1.69328732 -0.96192453  1.01334347]]


In [11]:
print(np.dot(a,a.T))

[[ 3.61375818 -1.17029021 -3.21892013 -1.8286077   1.92635453]
 [-1.17029021  0.37899027  1.04242468  0.59218176 -0.62383639]
 [-3.21892013  1.04242468  2.86722196  1.62881461 -1.71588166]
 [-1.8286077   0.59218176  1.62881461  0.9252988  -0.97475994]
 [ 1.92635453 -0.62383639 -1.71588166 -0.97475994  1.026865  ]]


In [12]:
assert(a.shape == (5,1))

# Explanation of Logistic Regression Cost function
$$\hat{y}^{(i)}= \sigma(w^T X^{(i)} + b) = \sigma(z^{(i)}) = \frac{1}{1+e^{-z}},\ where\ z^{(i)}= w^T X^{(i)} + b$$

$$\hat{y}= P(y=1|X)$$

$$If\ y=1:\ P(y|x) = \hat{y}$$
$$If\ y=0:\ P(y|x) = 1 - \hat{y}$$

$$P(y|x) = \hat{y}^{y}\cdot(1 - \hat{y})^{(1-y)}$$

$$\log{P(y|x)} = \log{\hat{y}^{y}\cdot(1 - \hat{y})^{(1-y)}} = y\cdot\log{\hat{y}} + (1 - y)\cdot\log(1-\hat{y}) = -L(\hat{y}, y)$$

# Cost on m examples
find maximum likelyhood estimation; choose parameters to maximize probability
$$\log{p(labels\ in\ training\ set)} = \log{\prod_{i=1}^{m}p(y^{(i)}|x^{(i)})} = \sum_{i=1}^{m}\log{p(y^{(i)}|x^{(i)})}$$
$$ = \sum_{i=1}^{m}-L(\hat{y}^{(i)}, y^{(i)})$$

minimize cost to maximize the probability
$$Cost\ = J(w,b) = \frac{1}{m}\cdot\sum_{i=1}^{m}-L(\hat{y}^{(i)}, y^{(i)})$$